{
 "title": "Computer Vision - Cats & Dogs (Workshop)",
 "tags": [
  "mlops",
  "computer-vision",
  "workshop"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "🗄️ Statut Base de Données",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cv_database_connected" }
   ]
  },
  {
   "title": "latence moyenne",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cv_inference_time_seconds_sum / cv_inference_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proportion de feedback positive et negative",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cv_user_feedback_total", "legendFormat": "{{feedback_type}}" }
   ]
  },
  {
   "title": "Taux de prédiction avec confidence trop faible",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cv_low_confidence_predictions_total) / sum(cv_inference_time_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latence moyenne",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(cv_inference_time_seconds_sum[5m]) / rate(cv_inference_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📊 Dernières Prédictions",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT created_at, prediction_result, ROUND(proba_cat::numeric, 2) as proba_cat, ROUND(proba_dog::numeric, 2) as proba_dog FROM predictions_feedback ORDER BY created_at DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Taille des images",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cv_abnormal_image_size_total", "legendFormat": "{{type}}" }
   ]
  }
 ]
}